### ISSUE TITLE
ember-native-dom-helpers duplicate ignored

### ISSUE THREAD

**Issue by kellyselden** [simonihmig/ember-test-helpers-codemod#18]
![screen shot 2018-04-18 at 1 44 50 pm](https://user-images.githubusercontent.com/602423/38957179-b8514106-430e-11e8-889d-d68ac2acf0c2.png)

**Comment by simonihmig** [comment]
To make sure I fully understand this: this is after running `ember-test-helpers-codemod --type=native-dom`, and the result is that `find` and `click` are used but not imported (anymore), right?

**Comment by kellyselden** [comment]
correct
