### ISSUE TITLE
Cannot read property 'callee' of undefined

### ISSUE THREAD

**Issue by efx** [simonihmig/ember-test-helpers-codemod#36]
I reproduced the failure [here](https://github.com/efx/ember-test-helpers-codemod/commit/d86475ae8d63d8e3547f640ab96934984a2b8313).
Frankly, this is 1 integration test out of 217 so I am going to refactor it. 
 I see 2 fixes:
1. add a `filter` with safety check before `replaceWith` [here](https://github.com/simonihmig/ember-test-helpers-codemod/blob/master/transforms/integration/transforms/set-value.js#L107). Downside is that this would leave a legacy pattern, perhaps we inform user and skip the file.
2. refactor that expression to handle this case.

I'm lazy and unmotivated, so I'd vote for 1. I can PR if wanted.

**Comment by simonihmig** [comment]
> I'm lazy and unmotivated, so I'd vote for 1. I can PR if wanted.

I'm ok with not converting it, as there will be many "odd" patterns which we won't be able to cover. So the philosophy here basically is to accept not converting something if in doubt, but to also *not* accept that this codemod converts to something invalid.

A PR would be highly appreciated! Thanks!
